# Generated by Django 3.0.6 on 2021-05-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201109_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='l_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='checkbox',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
