# Generated by Django 3.0.6 on 2021-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210529_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='f_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='l_name',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
